### ISSUE TITLE
Search modification

### ISSUE THREAD

**Issue by robustTechie** [someshkar/covid19india-cluster#97] opened 2020-03-26 14:30 UTC
**Is your feature request related to a problem? Please describe.**

As if the user search on P2P then he needs a patient number, it is the same for all cases either it is state or city. It would be great if a user would search city wise and state wise both.

**Describe the solution you'd like**
It should also show the result on the basis of the searched city or state. 

**Describe alternatives you've considered**
Or when city filter is selected it should provide an option to select a city. Same for the state. Also on hovering over a particular state, it will show statistics of that particular state.

![Screenshot from 2020-03-26 19-54-21](https://user-images.githubusercontent.com/52889867/77658342-91ce0200-6f9c-11ea-8df2-48b155a63442.png)

**Comment by sibeshkar** [comment] 2020-03-26 17:08
Duplicate of https://github.com/someshkar/covid19india-cluster/issues/81

**Closed by sibeshkar** 2020-03-26 17:08 UTC
